// This file was auto-generated by ML.NET Model Builder. 

using System;
using QnABotML.Model;

namespace QnABotML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Sentence = @"i didnt feel humiliated",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Emotion with predicted Emotion from sample data...\n\n");
            Console.WriteLine($"Sentence: {sampleData.Sentence}");
            Console.WriteLine($"\n\nPredicted Emotion value {predictionResult.Prediction} \nPredicted Emotion scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
