// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace QnABotML.Model
{
    public class ModelInput
    {
        [ColumnName("Sentence"), LoadColumn(0)]
        public string Sentence { get; set; }


        [ColumnName("Emotion"), LoadColumn(1)]
        public string Emotion { get; set; }


    }
}
